package com.seeyon.apps.cinda.po;


// Generated 2017-3-2 14:24:26 by Hibernate Tools 3.4.0.CR1



/**
 * TDocQuery generated by hbm2java
 */
public class TMeetingConfig implements java.io.Serializable {

  private long id;
  private String startTime;
  private String endTime;
  private int days;

  public TMeetingConfig() {
    super();
  }

  public TMeetingConfig(String startTime, String endTime, int days) {
    super();
    this.startTime = startTime;
    this.endTime = endTime;
    this.days = days;
  }


  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public int getDays() {
    return days;
  }

  public void setDays(int days) {
    this.days = days;
  }



}
