/**
 *
 *  File Authors: lucx
 */

var officeLang = {
	books_lend_succeed        : "You borrow books for the information has been submitted,please wait for the administrator's approval！",
	detail_info_office_type : "<li>To create a new category, click the 'New' button to open a dialog form and fill in the relevant info, set the category type as either 'vehicle', 'equipment', 'office supplies' or 'book'.</li><li>To modify a category, select an item on the list, and double-click it or click the 'Modify' button.</li><li>To delete a category, select an item on the list, and then click the 'Delete' button.</li>",
	detail_info_office_right: "<li>To assign a new administrator, click the 'New' button to open a dialog form and fill in the allow scope of authorizations.</li><li>To modify authorization for an administrator, select an item on the list, and double-click it or click the 'Modify' button.</li><li>To delete an administrator, select an item on the list, and then click the 'Delete' button</li>",
	detail_auto_apply: "<li>Through applying, you can transmit the demand of using vehicle in some time to the administrator. </li><li>Click the heading of a column to sort •the list alphabatically according to the selected column.</li>",
	detail_auto_audit: "<li>The vehicle administrator may review all vehicle requests and make approval decision as appropriate.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column. </li>",
	detail_auto_violate: "<li>The administrator registers the new record of violating the regulations of vehicle.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column. </li>",
	detail_info_stock_apply: "<li>To request the use of a particular vehicle, select the vehicle from the list and click the 'Apply' button.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_stock_audit: "<li> The administrator reviews any office supplies request and makes approval decision per available inventory as appropriate.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_auto_violate: "<li>The administrator records any violation of each vehicle use.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column. </li>",
	detail_info_office_registere : "<li>The vehicle administrator registers a new vehicle, and subsequently may modify or delete it.</li><li> Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_asset_reg: "<li>To register a newly acquired item by the administrator of 'office equipment', click the 'New' button.</li><li>To modify or delete an item, click the 'Modify' or the 'Delete' button. </li><li> Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_asset_listapp: "<li>To request the use of a particular office equipment item, select the item from the list and click the 'Apply' button.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>"	,
	detail_info_asset_listperm: "<li>The administrator reviews any office equipment request and makes approval decision per its availability as appropriate.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_asset_liststor: "<li>To display the lists of the approved office equipment requests, click the 'Sign-out/Return' button.</li><li>To record the item which was signed-out by a requestor, select the item and click the 'Sign-out' button.</li><li>To record the item which was returned by the user, select the item and click the 'Return' button.</li>",
	detail_info_book_listreg: "<li>To register a newly acquired book in the library, the administrator clicks the 'New' button.</li><li>To modify or delete an item, click the 'Modify' or the 'Delete' button.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_book_listapp: "<li> To borrow a particular book from the library, select the item from the list and click the 'Apply' button.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_book_listperm: "<li>The library administrator reviews any book request and makes approval decision per its availability as appropriate.</li><li>Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
	detail_info_book_liststor: "<li> To display the lists of the approved book requests, click the 'Sign-out/Return' button.</li><li>To record the item which was signed-out by a borrower, select the item and click the 'Sign-out' button.</li><li>To record the item which was returned by the borrower, select the item and click the 'Return' button.</li>",
    detail_info_auto_liststor: "<li>This page summarizes the list of applying had be approved.</li><li>The page of Sign Out is to register vehicle that are lend out.</li><li>The page of Sign Return is to register vehicle that are returned.</li>",
    auto_lend_succeed:"You borrow vehicle for the information has been submitted,please wait for the administrator's approval",
    auto_info_apply_nothing_prompt:"Had not found the information which you need",
    detail_info_stock_create:"<li>Office supplies administrator of the units could be office supplies information to be registered, and the information can be modified, deleted. </li><li> Click the heading of a column to sort the list alphabatically according to the selected column.</li>",
    detail_info_myApply: "<li>You can manage their own vehicles, office equipment, office supplies and books for information.</li><li>You can edit unaudited and not approved the application, the application of information can be deleted.</li>",
	detail_info_meetingroom_sigin: "<li> conference room of the unit administrator can register information on the conference room, and can modify this information, delete. </ li> \ n <li> click the list header can be quickly sorted </ li> " ,
    detail_info_meetingroom_application: "<li> users to convey the application to the administrator of a conference room at a certain time of usage requirements, and can see the use of conference room </ li> \ n <li> click the list header can be quickly Sort </ li> ", 
    detail_info_meetingroom_pass: "<li> Meeting Room Manager for details and free under the circumstances to decide whether to apply. </ li> \ n <li> click the list header can be quickly sorted. </ li>", 
    detail_info_meetingroom_cancel: "<li> users to the administrator of the conference rooms have been issued to withdraw the application. </ li> \ n <li> click the list header can be quickly sorted. </ li>", 
    detail_info_meetingroom_count: "<li> Meeting Room Manager statistics of a time period of the meeting room usage. </ li> \ n <li> click the list header can be quickly sorted. </ li>"
}