CREATE TABLE [ADDRESSBOOK](
[ID] [bigint] NOT NULL,
[MEMBER_ID] [bigint] NULL,
[CREATE_DATE] [datetime] NULL,
[UPDATE_DATE] [datetime] NULL,
[EXT_ATTR_1] [nvarchar](1024) NULL,
[EXT_ATTR_2] [nvarchar](1024) NULL,
[EXT_ATTR_3] [nvarchar](1024) NULL,
[EXT_ATTR_4] [nvarchar](1024) NULL,
[EXT_ATTR_5] [nvarchar](1024) NULL,
[EXT_ATTR_6] [nvarchar](1024) NULL,
[EXT_ATTR_7] [nvarchar](1024) NULL,
[EXT_ATTR_8] [nvarchar](1024) NULL,
[EXT_ATTR_9] [nvarchar](1024) NULL,
[EXT_ATTR_10] [nvarchar](1024) NULL,
[EXT_ATTR_11] [NUMERIC](19, 4) NULL,
[EXT_ATTR_12] [NUMERIC](19, 4) NULL,
[EXT_ATTR_13] [NUMERIC](19, 4) NULL,
[EXT_ATTR_14] [NUMERIC](19, 4) NULL,
[EXT_ATTR_15] [NUMERIC](19, 4) NULL,
[EXT_ATTR_16] [NUMERIC](19, 4) NULL,
[EXT_ATTR_17] [NUMERIC](19, 4) NULL,
[EXT_ATTR_18] [NUMERIC](19, 4) NULL,
[EXT_ATTR_19] [NUMERIC](19, 4) NULL,
[EXT_ATTR_20] [NUMERIC](19, 4) NULL,
[EXT_ATTR_21] [datetime] NULL,
[EXT_ATTR_22] [datetime] NULL,
[EXT_ATTR_23] [datetime] NULL,
[EXT_ATTR_24] [datetime] NULL,
[EXT_ATTR_25] [datetime] NULL,
[EXT_ATTR_26] [datetime] NULL,
[EXT_ATTR_27] [datetime] NULL,
[EXT_ATTR_28] [datetime] NULL,
[EXT_ATTR_29] [datetime] NULL,
[EXT_ATTR_30] [datetime] NULL,
CONSTRAINT [PK_ADDRESSBOOK] PRIMARY KEY NONCLUSTERED
)
USE [1210]
GO

/****** Object:  Table [dbo].[FORM_DEFINITION]    Script Date: 12/12/2018 17:30:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORM_DEFINITION](
[ID] [bigint] NOT NULL,
[NAME] [nvarchar](255) NULL,
[CREATE_ID] [bigint] NULL,
[CREATE_TIME] [datetime] NULL,
[FORM_TYPE] [smallint] NULL,
[CATEGORY_ID] [bigint] NULL,
[USE_FLAG] [smallint] NULL,
[STATE] [smallint] NULL,
[DELETE_FLAG] [smallint] NULL,
[FIELD_INFO] [ntext] NULL,
[VIEW_INFO] [ntext] NULL,
[QUERY_INFO] [ntext] NULL,
[REPORT_INFO] [ntext] NULL,
[TRIGGER_INFO] [ntext] NULL,
[APPBIND_INFO] [ntext] NULL,
[EXTENSIONS_INFO] [ntext] NULL,
[MODIFY_TIME] [datetime] NULL,
[FORM_STYLE] [ntext] NULL,
[PREPARE_FLAG] [smallint] NULL,
[SOURCE_TYPE] [nvarchar](255) NULL,
 PRIMARY KEY ()
(
[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[FORM_DEFINITION] ADD  DEFAULT ((0)) FOR [FORM_TYPE]
GO

ALTER TABLE [dbo].[FORM_DEFINITION] ADD  DEFAULT ((0)) FOR [USE_FLAG]
GO

ALTER TABLE [dbo].[FORM_DEFINITION] ADD  DEFAULT ((2)) FOR [PREPARE_FLAG]
GO


