<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade" xmlns:intf="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns1="urn:client.wscusbdwebservicefacade" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema targetNamespace="urn:client.wscusbdwebservicefacade" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
   <complexType name="WSInvokeException">
    <sequence/>
   </complexType>
  </schema>
 </wsdl:types>

   <wsdl:message name="importBDRequest">

      <wsdl:part name="bdType" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="bdDataJSON" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="bdStatus" type="xsd:int">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="importBDResponse">

      <wsdl:part name="importBDReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="WSInvokeException">

      <wsdl:part name="fault" type="tns1:WSInvokeException">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="WSWSCusBDWebServiceFacadeSrvProxy">

      <wsdl:operation name="importBD" parameterOrder="bdType bdDataJSON bdStatus">

         <wsdl:input message="intf:importBDRequest" name="importBDRequest">

       </wsdl:input>

         <wsdl:output message="intf:importBDResponse" name="importBDResponse">

       </wsdl:output>

         <wsdl:fault message="intf:WSInvokeException" name="WSInvokeException">

       </wsdl:fault>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WSWSCusBDWebServiceFacadeSoapBinding" type="intf:WSWSCusBDWebServiceFacadeSrvProxy">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="importBD">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="importBDRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.app.webservice.custom.eas.kingdee.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="importBDResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade" use="encoded"/>

         </wsdl:output>

         <wsdl:fault name="WSInvokeException">

            <wsdlsoap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" name="WSInvokeException" namespace="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade" use="encoded"/>

         </wsdl:fault>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WSWSCusBDWebServiceFacadeSrvProxyService">

      <wsdl:port binding="intf:WSWSCusBDWebServiceFacadeSoapBinding" name="WSWSCusBDWebServiceFacade">

         <wsdlsoap:address location="http://10.10.10.98/ormrpc/services/WSWSCusBDWebServiceFacade"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
