<?xml version="1.0" encoding="UTF-8"?>

        <wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns1="urn:client.cusscmwebservicefacade" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:intf="http://localhost:6888/ormrpc/services/WSCusSCMWebServiceFacade" xmlns:impl="http://localhost:6888/ormrpc/services/WSCusSCMWebServiceFacade" xmlns:apachesoap="http://xml.apache.org/xml-soap" targetNamespace="http://localhost:6888/ormrpc/services/WSCusSCMWebServiceFacade">

    <!--WSDL created by Apache Axis version: 1.4 Built on Apr 22, 2006 (06:55:48 PDT)-->



    <wsdl:types>


    <schema targetNamespace="urn:client.cusscmwebservicefacade" xmlns="http://www.w3.org/2001/XMLSchema">

    <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>


    <complexType name="WSInvokeException">

    <sequence/>

</complexType>

</schema>

</wsdl:types>


    <wsdl:message name="WSInvokeException">

    <wsdl:part name="fault" type="tns1:WSInvokeException"> </wsdl:part>

</wsdl:message>


    <wsdl:message name="importBillRequest">

    <wsdl:part name="billDataJSON" type="xsd:string"> </wsdl:part>

    <wsdl:part name="billStatus" type="xsd:int"> </wsdl:part>

</wsdl:message>


    <wsdl:message name="importBillResponse">

    <wsdl:part name="importBillReturn" type="xsd:string"> </wsdl:part>

</wsdl:message>


    <wsdl:portType name="WSCusSCMWebServiceFacadeSrvProxy">


    <wsdl:operation name="importBill" parameterOrder="billDataJSON billStatus">

    <wsdl:input name="importBillRequest" message="impl:importBillRequest"> </wsdl:input>

    <wsdl:output name="importBillResponse" message="impl:importBillResponse"> </wsdl:output>

    <wsdl:fault name="WSInvokeException" message="impl:WSInvokeException"> </wsdl:fault>

</wsdl:operation>

</wsdl:portType>


    <wsdl:binding name="WSCusSCMWebServiceFacadeSoapBinding" type="impl:WSCusSCMWebServiceFacadeSrvProxy">

    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>


    <wsdl:operation name="importBill">

    <wsdlsoap:operation soapAction=""/>


    <wsdl:input name="importBillRequest">

    <wsdlsoap:body namespace="http://webservice.app.webservice.custom.eas.kingdee.com" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>

</wsdl:input>


    <wsdl:output name="importBillResponse">

    <wsdlsoap:body namespace="http://localhost:6888/ormrpc/services/WSCusSCMWebServiceFacade" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>

</wsdl:output>


    <wsdl:fault name="WSInvokeException">

    <wsdlsoap:fault namespace="http://localhost:6888/ormrpc/services/WSCusSCMWebServiceFacade" name="WSInvokeException" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>

</wsdl:fault>

</wsdl:operation>

</wsdl:binding>


    <wsdl:service name="WSCusSCMWebServiceFacadeSrvProxyService">


    <wsdl:port name="WSCusSCMWebServiceFacade" binding="impl:WSCusSCMWebServiceFacadeSoapBinding">

    <wsdlsoap:address location="http://10.42.1.210:6888/ormrpc/services/WSCusSCMWebServiceFacade"/>

</wsdl:port>

</wsdl:service>

</wsdl:definitions>