CREATE TABLE edoc_form_file_relation(ID int8 DEFAULT 0,FILE_ID int8 NOT NULL,EDOC_FORM_ID int8 NOT NULL,DOUBLE_FORM  boolean DEFAULT true,FILE_TYPE varchar(20) DEFAULT 'pdf');
CREATE TABLE edoc_sendform_file_relation (ID int8  DEFAULT 0,EDOC_ID int8 NOT NULL,FILE_ID int8 NOT NULL,FILE_TYPE varchar(20) DEFAULT 'pdf',SIGN_STRING text,OPINIONS text);
CREATE TABLE leader_window (org_depart_id int8,name varchar(255) COLLATE "default",duty varchar(300) COLLATE "default",content text COLLATE "default",att_flag varchar(11) COLLATE "default",self_image_name varchar(255) COLLATE "default",id int8 NOT NULL)WITH (OIDS=FALSE);
COMMENT ON COLUMN leader_window.org_depart_id IS '组织管理员ID或者单位人员ID';
COMMENT ON COLUMN leader_window.name IS '左侧-姓名';
COMMENT ON COLUMN leader_window.duty IS '职务';
COMMENT ON COLUMN leader_window.content IS '其他人员信息';
COMMENT ON COLUMN leader_window.att_flag IS '是否上传了附件';
COMMENT ON COLUMN leader_window.self_image_name IS '用户上传图片名';
ALTER TABLE leader_window ADD PRIMARY KEY (id);

INSERT INTO "priv_resource" ("id", "resource_name", "resource_type", "resource_category", "navurl", "resource_code", "resource_order", "moduleid", "path", "is_control", "is_show", "createdate", "createuserid", "updatedate", "updateuserid", "ext1", "ext2", "ext3", "ext4", "ext5", "ext6") VALUES (-957743153815600210, '领导之窗设置', 0, 2, '/portal/leaderwindow.do?method=creatLeaderWindow', 'T02_creatLeaderWindow', NULL, 'none', NULL, 1, 0, '2013-3-19 14:08:40', NULL, '2013-3-7 10:59:29', NULL, '0', '0', '0', 1, NULL, NULL);
INSERT INTO "priv_menu" ("id", "name", "icon", "target", "sortid", "pluginid", "path", "createdate", "createuserid", "updatedate", "updateuserid", "ext1", "ext2", "ext3", "ext4", "ext5", "ext6", "ext7", "ext8", "ext9", "ext10", "ext11", "ext12", "ext13", "ext14", "ext15", "ext16", "ext17", "ext18", "ext19", "ext20", "ext21") VALUES (957397852094811900, 'edoc.system.menuname.leaderWindow', 'b.gif', 'mainfrm', 13, NULL, '043013', '2012-8-27 00:00:00', NULL, '2012-8-27 00:00:00', NULL, '0', '2', '', 1, NULL, NULL, '领导之窗设置', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "priv_menu" ("id", "name", "icon", "target", "sortid", "pluginid", "path", "createdate", "createuserid", "updatedate", "updateuserid", "ext1", "ext2", "ext3", "ext4", "ext5", "ext6", "ext7", "ext8", "ext9", "ext10", "ext11", "ext12", "ext13", "ext14", "ext15", "ext16", "ext17", "ext18", "ext19", "ext20", "ext21") VALUES (857397852094811900, 'edoc.system.menuname.leaderWindow', 'b.gif', 'mainfrm', 15, NULL, '025025', '2012-8-27 00:00:00', NULL, '2012-8-27 00:00:00', NULL, '0', '2', '', 1, NULL, NULL, '领导之窗设置', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "priv_menu_resource" ("id", "menuid", "resourceid", "enter_resource") VALUES (971693576735640503, 957397852094811900, -957743153815600210, 1);
INSERT INTO "priv_menu_resource" ("id", "menuid", "resourceid", "enter_resource") VALUES (871693576735640503, 857397852094811900, -957743153815600210, 1);
INSERT INTO "priv_role_resource" ("id", "resourceid", "roleid", "menuid", "modifiable") VALUES (-93781319006404403, -957743153815600210, -3739927258183285747, 957397852094811900, NULL);
INSERT INTO "priv_role_resource" ("id", "resourceid", "roleid", "menuid", "modifiable") VALUES (-83781319006404403, -957743153815600210, -2989205846588111483, 857397852094811900, NULL);

INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('201', '人事任免', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('202', '干部选拔', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('203', '任前公示', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('204', '通知公告', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('205', '领导讲话', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('206', '部门发展规划', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('207', '统计信息', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');
INSERT INTO  "bul_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "is_auditor_modify") VALUES('208', '财政信息', '1', '', '0', '1', '0', NULL, '2008-03-29 12:05:03', '0', '2008-03-29 12:05:03', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0');

INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('301', '领导动态', '1', '领导动态', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('302', '省政府动态', '1', '省政府动态', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('303', '部门动态', '1', '部门动态', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('304', '区县热点', '1', '区县热点', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('305', '政府会议', '1', '政府会议', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('306', '重大项目', '1', '重大项目', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('307', '规划实施', '1', '规划实施', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');
INSERT INTO "news_type" ("id", "type_name", "used_flag", "description", "top_count", "audit_flag", "audit_user", "default_template_id", "create_date", "create_user", "update_date", "update_user", "accountid", "spacetype", "ext1", "ext2", "sort_num", "outter_permit", "is_auditor_modify") VALUES ('310', '新闻发布会', '1', '新闻发布会', '3', '1', '0', null, '2008-03-29 11:30:40', '0', '2008-03-29 11:30:40', '0', '-1730833917365171641', '3', 'NULL', 'NULL', '0', '0', '0');


INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column") VALUES ('501', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '3', '2');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('502', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '0', '0');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('503', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '4', '2');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('504', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '1', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('505', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '3', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('506', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '4', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('507', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '1', '2');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column") VALUES('508', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '2', '2');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('509', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '0', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('510', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '5', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('511', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '0', '2');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('512', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '2', '1');
INSERT INTO "portal_page_portlet" ("id", "parent_id", "page_id", "name", "type", "skin", "layout_row", "layout_column")VALUES('513', '-2774745272948209325', NULL, 'seeyon::sectionPortlet', NULL, NULL, '5', '2');

INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('601', '504', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('602', '507', 'count:0', '5');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-603', '510', 'columnsName:0', '部门发展规划');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-604', '504', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-605', '512', 'columnsStyle:2', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-606', '505', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-607', '506', 'panel:0', 'designated');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-608', '501', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-609', '511', 'columnsName:0', '通知公告');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-610', '513', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-611', '505', 'columnsName:0', '人事信息');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-612', '510', 'rowList:1', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-613', '503', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-614', '512', 'count:1', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-615', '503', 'sections', 'singleBoardGroupNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-616', '510', 'count:1', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-617', '505', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-618', '502', 'columnsStyle:0', '0');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-619', '506', 'designated_value:0', '310');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-620', '505', 'designated_name:0', '指定板块');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-622', '510', 'columnsName:1', '规划实施');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-623', '507', 'panel:0', 'designated');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-624', '510', 'columnsStyle:1', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-625', '507', 'columnsName:0', '领导动态');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-626', '503', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-627', '513', 'rowList:1', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-628', '507', 'columnsStyle:1', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-629', '513', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-630', '510', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-631', '513', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-632', '512', 'count:2', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-633', '506', 'columnsStyle:0', 'imageandtitle');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-634', '513', 'singleBoardId:1', '208');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-635', '507', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-636', '502', 'fontSize:0', '4');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-640', '512', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-641', '502', 'backgroundTile:0', 'inherit');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-642', '503', 'columnsName:0', '重大项目');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-643', '512', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-644', '502', 'fontColor:0', '0');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-645', '508', 'sections', 'viewLeaderWindowSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-646', '512', 'speed:1', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-647', '504', 'columnsName:0', '政务要闻');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-648', '510', 'singleBoardId:1', '307');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-649', '509', 'sections', 'groupImageNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-650', '513', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-401', '512', 'singleBoardId:0', '302');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-402', '513', 'singleBoardId:0', '207');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-403', '506', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-404', '510', 'sections', 'singleBoardGroupBulletinSection,singleBoardGroupNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-405', '501', 'singleBoardId:0', '305');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-406', '503', 'singleBoardId:0', '306');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-407', '505', 'panel:0', 'designated');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-708', '507', 'columnsStyle:0', 'imageandlist');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-408', '513', 'speed:1', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-409', '506', 'columnsName:0', '新闻发布会');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-410', '501', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-411', '505', 'sections', 'groupBulletinSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-412', '507', 'count:1', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('-413', '511', 'rowList:0', 'subject,publishDate,aunit');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('414', '507', 'singleBoardId:1', '205');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('415', '504', 'singleBoardId:0', '1');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('416', '502', 'inherit_name:0', '平铺');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('417', '510', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('418', '512', 'columnsName:1', '部门动态');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('419', '503', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('421', '502', 'sections', 'banner');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('422', '512', 'columnsStyle:1', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('423', '506', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('424', '510', 'singleBoardId:0', '206');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('425', '511', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('426', '512', 'speed:2', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('427', '513', 'columnsName:1', '财政信息');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('428', '501', 'columnsName:0', '政府会议');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('429', '507', 'speed:1', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('430', '506', 'sections', 'groupImageNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('431', '510', 'rowList:0', 'subject,aunit');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('432', '510', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('433', '513', 'columnsStyle:1', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('434', '507', 'designated_name:0', '指定板块');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('435', '501', 'sections', 'singleBoardGroupNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('701', '506', 'count:0', '2');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('702', '512', 'rowList:2', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('703', '502', 'fontStyle:0', '1');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('704', '511', 'count:0', '13');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('705', '512', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('706', '507', 'sections', 'groupImageNewsSection,singleBoardGroupBulletinSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('707', '512', 'columnsName:2', '区县热点');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('708', '504', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('709', '501', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('710', '506', 'designated_name:0', '指定板块');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('711', '511', 'sections', 'singleBoardGroupBulletinSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('712', '512', 'columnsName:0', '省政府动态');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('713', '505', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('714', '512', 'sections', 'singleBoardGroupNewsSection,singleBoardGroupNewsSection,singleBoardGroupNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('715', '513', 'sections', 'singleBoardGroupBulletinSection,singleBoardGroupBulletinSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('716', '504', 'sections', 'singleBoardGroupNewsSection');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('717', '507', 'rowList:1', 'subject,publishDate');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('718', '513', 'count:1', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('719', '504', 'columnsStyle:0', 'list');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('720', '507', 'rowList:0', 'subject');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('721', '507', 'columnsName:1', '领导讲话');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('722', '505', 'rowList:0', 'subject,type');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('723', '511', 'singleBoardId:0', '204');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('724', '501', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('725', '507', 'designated_value:0', '301');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('726', '512', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('727', '502', 'slogan:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('728', '511', 'speed:0', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('729', '502', 'height:0', '60');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('730', '510', 'speed:1', '');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('731', '512', 'singleBoardId:2', '304');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('732', '503', 'count:0', '8');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('733', '505', 'designated_value:0', '201,203,202');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('734', '513', 'columnsName:0', '统计信息');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('735', '512', 'singleBoardId:1', '303');
INSERT INTO "portal_portlet_property" ("id", "entity_id", "property_name", "property_value") VALUES ('736', '512', 'rowList:1', 'subject');