CREATE TABLE "log_entry"
   (	"id" NUMBER(20,0) NOT NULL ENABLE,
	"name" NVARCHAR2(255),
	"create_time" DATE,
	"update_time" DATE,
	"status" NUMBER(6,0),
	"msg" NCLOB,
	"level" NVARCHAR2(255),
	"success" NUMBER(6,0),
	"data" NVARCHAR2(512),
	 PRIMARY KEY ("id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "V5XSPACE"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "V5XSPACE"
 LOB ("msg") STORE AS BASICFILE (
  TABLESPACE "V5XSPACE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING )